id: A858EE515
title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of the
  Guru (Lama Sangdü)'
type: translation
pechas:
- IFE9BDC9F
- I0B344334
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:03:20.307357
  last_modified_at: 2023-01-04 13:03:20.307362
  collections:
  - Minling Terchen Gyurme Dorje Series
  - Works of Tibetan Masters
alignment_to_base:
  IFE9BDC9F/AC67: 98F2
  I0B344334/EA9E: 98F2
